services:
  db:
    image: postgres:latest
    ports: 
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: login_api
    volumes: 
    - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data:

